package io.pokemonj2.curtis;

public enum Pokenum
{
	BULBASAUR(1, "BULBASAUR"),
	IVYSAUR(2, "IVYSAUR"),
	VENUSAUR(3, "VENUSAUR"),
	CHARMANDER(4, "CHARMANDER"),
	CHARMELEON(5, "CHARMELEON"),
	CHARIZARD(6, "CHARIZARD"),
	SQUIRTLE(7, "SQUIRTLE"),
	WARTORTLE(8, "WARTORTLE"),
	BLASTOISE(9, "BLASTOISE"),
	CATERPIE(10, "CATERPIE"),
	METAPOD(11, "METAPOD"),
	BUTTERFREE(12, "BUTTERFREE"),
	WEEDLE(13, "WEEDLE"),
	KAKUNA(14, "KAKUNA"),
	BEEDRILL(15, "BEEDRILL"),
	PIDGEY(16, "PIDGEY"),
	PIDGEOTTO(17, "PIDGEOTTO"),
	PIDGEOT(18, "PIDGEOT"),
	RATTATA(19, "RATTATA"),
	RATICATE(20, "RATICATE"),
	SPEAROW(21, "SPEAROW"),
	FEAROW(22, "FEAROW"),
	EKANS(23, "EKANS"),
	ARBOK(24, "ARBOK"),
	PIKACHU(25, "PIKACHU"),
	RAICHU(26, "RAICHU"),
	SANDSHREW(27, "SANDSHREW"),
	SANDSLASH(28, "SANDSLASH"),
	NIDORAN_F(29, "NIDORAN"),
	NIDORINA(30, "NIDORINA"),
	NIDOQUEEN(31, "NIDOQUEEN"),
	NIDORAN_M(32, "NIDORAN"),
	NIDORINO(33, "NIDORINO"),
	NIDOKING(34, "NIDOKING"),
	CLEFAIRY(35, "CLEFAIRY"),
	CLEFABLE(36, "CLEFABLE"),
	VULPIX(37, "VULPIX"),
	NINETAILS(38, "NINETAILS"),
	JIGGLYPUFF(39, "JIGGLYPUFF"),
	WIGGLYTUFF(40, "WIGGLYTUFF"),
	ZUBAT(41, "ZUBAT"),
	GOLBAT(42, "GOLBAT"),
	ODDISH(43, "ODDISH"),
	GLOOM(44, "GLOOM"),
	VILEPLUME(45, "VILEPLUME"),
	PARAS(46, "PARAS"),
	PARASECT(47, "PARASECT"),
	VENONAT(48, "VENONAT"),
	VENOMOTH(49, "VENOMOTH"),
	DIGLETT(50, "DIGLETT"),
	DUGTRIO(51, "DUGTRIO"),
	MEOWTH(52, "MEOWTH"),
	PERSIAN(53, "PERSIAN"),
	PSYDUCK(54, "PSYDUCK"),
	GOLDUCK(55, "GOLDUCK"),
	MANKEY(56, "MANKEY"),
	PRIMEAPE(57, "PRIMEAPE"),
	GROWLITHE(58, "GROWLITHE"),
	ARCANINE(59, "ARCANINE"),
	POLIWAG(60, "POLIWAG"),
	POLIWHIRL(61, "POLIWHIRL"),
	POLIWRATH(62, "POLIWRATH"),
	ABRA(63, "ABRA"),
	KADABRA(64, "KADABRA"),
	ALAKAZAM(65, "ALAKAZAM"),
	MACHOP(66, "MACHOP"),
	MACHOKE(67, "MACHOKE"),
	MACHAMP(68, "MACHAMP"),
	BELLSPROUT(69, "BELLSPROUT"),
	WEEPINBELL(70, "WEEPINBELL"),
	VICTREEBEL(71, "VICTREEBEL"),
	TENTACOOL(72, "TENTACOOL"),
	TENTACRUEL(73, "TENTACRUEL"),
	GEODUDE(74, "GEODUDE"),
	GRAVELER(75, "GRAVELER"),
	GOLEM(76, "GOLEM"),
	PONYTA(77, "PONYTA"),
	RAPIDASH(78, "RAPIDASH"),
	SLOWPOKE(79, "SLOWPOKE"),
	SLOWBRO(80, "SLOWBRO"),
	MAGNEMITE(81, "MAGNEMITE"),
	MAGNETON(82, "MAGNETON"),
	FARFETCHD(83, "FARFETCH'D"),
	DODUO(84, "DODUO"),
	DODRIO(85, "DODRIO"),
	SEEL(86, "SEEL"),
	DEWGONG(87, "DEWGONG"),
	GRIMER(88, "GRIMER"),
	MUK(89, "MUK"),
	SHELLDER(90, "SHELLDER"),
	CLOYSTER(91, "CLOYSTER"),
	GASTLY(92, "GASTLY"),
	HAUNTER(93, "HAUNTER"),
	GENGAR(94, "GENGAR"),
	ONIX(95, "ONIX"),
	DROWZEE(96, "DROWZEE"),
	HYPNO(97, "HYPNO"),
	KRABBY(98, "KRABBY"),
	KINGLER(99, "KINGLER"),
	VOLTORB(100, "VOLTORB"),
	ELECTRODE(101, "ELECTRODE"),
	EXEGGCUTE(102, "EXEGGCUTE"),
	EXEGGUTOR(103, "EXEGGUTOR"),
	CUBONE(104, "CUBONE"),
	MAROWAK(105, "MAROWAK"),
	HITMONLEE(106, "HITMONLEE"),
	HITMONCHAN(107, "HITMONCHAN"),
	LICKITUNG(108, "LICKITUNG"),
	KOFFING(109, "KOFFING"),
	WEEZING(110, "WEEZING"),
	RHYHORN(111, "RHYHORN"),
	RHYDON(112, "RHYDON"),
	CHANSEY(113, "CHANSEY"),
	TANGELA(114, "TANGELA"),
	KANGASKHAN(115, "KANGASKHAN"),
	HORSEA(116, "HORSEA"),
	SEADRA(117, "SEADRA"),
	GOLDEEN(118, "GOLDEEN"),
	SEAKING(119, "SEAKING"),
	STARYU(120, "STARYU"),
	STARMIE(121, "STARMIE"),
	MR_MIME(122, "MR. MIME"),
	SCYTHER(123, "SCYTHER"),
	JYNX(124, "JYNX"),
	ELECTABUZZ(125, "ELECTABUZZ"),
	MAGMAR(126, "MAGMAR"),
	PINSIR(127, "PINSIR"),
	TAUROS(128, "TAUROS"),
	MAGIKARP(129, "MAGIKARP"),
	GYARADOS(130, "GYARADOS"),
	LAPRAS(131, "LAPRAS"),
	DITTO(132, "DITTO"),
	EEVEE(133, "EEVEE"),
	VAPOREON(134, "VAPOREON"),
	JOLTEON(135, "JOLTEON"),
	FLAREON(136, "FLAREON"),
	PORYGON(137, "PORYGON"),
	OMANYTE(138, "OMANYTE"),
	OMASTAR(139, "OMASTAR"),
	KABUTO(140, "KABUTO"),
	KABUTOPS(141, "KABUTOPS"),
	AERODACTYL(142, "AERODACTYL"),
	SNORLAX(143, "SNORLAX"),
	ARTICUNO(144, "ARTICUNO"),
	ZAPDOS(145, "ZAPDOS"),
	MOLTRES(146, "MOLTRES"),
	DRATINI(147, "DRATINI"),
	DRAGONAIR(148, "DRAGONAIR"),
	DRAGONITE(149, "DRAGONITE"),
	MEWTWO(150, "MEWTWO"),
	MEW(151, "MEW");
	
	private int dexNo;
	private String name;
	
	Pokenum(int dex, String name)
	{
		dexNo = dex;
		this.name = name;
	}
	
	public int getDexNum()
	{
		return dexNo;
	}
	
	public String getName()
	{
		return name;
	}
	
	public static Pokenum fromDexNo(int num)
	{
		for (Pokenum p : values())
		{
			if (p.getDexNum() == num)
			{
				return p;
			}
		}
		return BULBASAUR;
	}
}